algorithm: mixmatch
cls_algorithm: fixmatch
save_dir: ./saved_models/nlp
save_name: mixmatch_fixmatch_yelp_review_lb250_s0
resume: True
load_path: ./saved_models/nlp/mixmatch_fixmatch_yelp_review_lb250_s0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_log_iter: 256
num_warmup_iter: 5120
num_labels: 250
batch_size: 8
eval_batch_size: 8
ema_m: 0.0
uratio: 1
reg_ulb_loss_ratio: 0.1
reg_unsup_warm_up: 0.4
reg_mixup_alpha: 0.5
reg_mixup_manifold: True
cls_loss_ratio: 0.2
cls_ulb_loss_ratio: 1.0
hard_label: True
T: 0.5
p_cutoff: 0.95
optim: AdamW
lr: 1e-05
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip_grad: 0.0
use_cat: False
reg_criterion: l1
net: bert_base
net_from_name: False
use_pretrain: True
pretrain_path: google/bert_uncased_L-4_H-512_A-8
data_dir: ./data
dataset: yelp_review
train_sampler: RandomSampler
num_workers: 4
max_length: 512
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
