algorithm: mixmatch
cls_algorithm: None
save_dir: ./saved_models/classic_cv
save_name: mixmatch_none_utkface_lb50_s0
resume: True
load_path: ./saved_models/classic_cv/mixmatch_none_utkface_lb50_s0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_log_iter: 256
num_labels: 50
batch_size: 32
eval_batch_size: 256
ema_m: 0.999
uratio: 1
reg_ulb_loss_ratio: 0.1
reg_unsup_warm_up: 0.4
reg_mixup_alpha: 0.5
optim: SGD
lr: 0.01
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip_grad: 0.0
use_cat: True
reg_criterion: l1
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: utkface
train_sampler: RandomSampler
num_workers: 4
crop_ratio: 0.875
img_size: 40
preload: False
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
