algorithm: fullysupervised
save_dir: ./saved_models/audio
save_name: fullysupervised_bvcc_s0
resume: True
load_path: ./saved_models/audio/fullysupervised_bvcc_s0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_log_iter: 256
num_warmup_iter: 5120
batch_size: 8
eval_batch_size: 16
ema_m: 0.0
optim: AdamW
lr: 2e-06
momentum: 0.9
weight_decay: 2e-05
layer_decay: 0.75
amp: False
clip_grad: 0.0
use_cat: False
reg_criterion: l1
net: whisper_base
net_from_name: False
use_pretrain: True
pretrain_path: openai/whisper-base
data_dir: ./data
dataset: bvcc
train_sampler: RandomSampler
num_workers: 8
max_length_seconds: 6.0
sample_rate: 16000
preload: True
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
